[project]
name = "glade-backend"
version = "0.0.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.116.1",
    "httpx>=0.28.1",
    "uvicorn[standard]>=0.35.0",
    "python-dateutil>=2.9.0",
    "python-dotenv>=1.1.1"
]
